### ISSUE TITLE
vitest 4.1.5 broke async vi.mock factories — SPA tests fail with 'orig is not a function'

### ISSUE THREAD

**Issue by unforced** [ParachuteComputer/parachute-hub#164]
## Symptom

All `web/ui/src/**/*.test.tsx` files that use `vi.mock(..., async (orig) => { ... })` factories fail on `main` with:

```
TypeError: orig is not a function
```

Pre-existing on `main` — not introduced by #163. Reviewer flagged during #163 review.

## Affected files

- `web/ui/src/routes/VaultsList.test.tsx`
- `web/ui/src/lib/api.test.ts`
- (~20 tests total — all the SPA unit suites that import from `../lib/api.ts` and partially mock it)

## Root cause

vitest 4.1.5 regression: the async-factory `(orig) => ...` signature for `vi.mock` no longer receives `orig` as a callable. Pinned-version tests pass; bumping to 4.1.5 (which the lockfile pulled in transitively) breaks the factory's `await orig()` pattern.

## Impact

Blocks all SPA unit-test coverage. Typecheck + biome + the `bun test ./src` suite all stay green, so it's been silent.

## Fix options

1. **Pin vitest to 4.1.4** in `web/ui/package.json` until upstream regression-fixes.
2. **Rewrite the affected `vi.mock` factories** to not rely on the `orig` callable — explicit re-import instead of `await orig()`.

Option 1 is lower risk; option 2 is more durable. Either way, the gates need to actually run the SPA suite (`bun run --cwd web/ui test`) so this kind of regression doesn't get back in.

## Out of scope

Don't fold into #163. File as standalone — the SPA test infra is its own deliverable.

**Comment by unforced** [comment]
No longer reproducible on main post-#165. Re-ran `cd web/ui && bun run test` against fresh main (vitest 4.1.5, all 5 test files / 46 tests pass). Including `Permissions.test.tsx`, which uses the exact `vi.mock(..., async (orig) => { const actual = (await orig()) as typeof api; return { ...actual, ... } })` factory pattern that was originally suspected broken. Closing as not-currently-reproducible; reopen if it resurfaces.
